### ISSUE TITLE
Sữa lỗi

### ISSUE THREAD

**Issue by biithanh** [flashbots/builder#25]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Ruteri** [comment]
Hi @biithanh 
Unfortunately I don't understand.
Please re-open the issue with a description in English so that everyone involved can understand and help.
