### ISSUE TITLE
Are sandwich attacks actually possible on Flashbots?

### ISSUE THREAD

**Issue by randoum** [flashbots/builder#38]
I'm a newbie regarding the blockchain, so I may be wrong all along, but here it is. 

While working on my project I found some transactions that may look like sandwich attacks, even though they were validated by the Flashbots builder. And I'm certain that Flashbots won't allow sandwich attacks. Could you explain to me what's going on?

- On block 16318855, the transaction at position 0 from 0xb58...f7b is swapping WETH to RPL on UniswapV3 (0xe42...b45).
- Then another wallet performs a few arbitrage swaps at position 1, including a WETH-RPL swap on the same UniswapV3 pair  (0xe42...b45)
- And at position 2, the first wallet swaps back RPL to WETH on that very same UniswapV3 pair, making an 0.5 eth profit.

The same kind of scenario happens in the same block at positions 5, 6, and 7.

**Comment by Ruteri** [comment]
> And I'm certain that Flashbots won't allow sandwich attacks

Please do expand on why that is the thinking

**Comment by randoum** [comment]
> > And I'm certain that Flashbots won't allow sandwich attacks
> 
> Please do expand on why that is the thinking

From your condescending response I understand that Flashbots is not protecting against sandwich attacks. Misconception on my end.
