### ISSUE TITLE
MevGasPrice shouldn't account for coinbase transfer when the TX is in the mempoll

### ISSUE THREAD

**Issue by krasi-georgiev** [flashbots/builder#54]
When the TX is in the mempool the coinbase transfer should also be ignored.

It this code
https://github.com/flashbots/builder/blob/8caba1f96ff5adf5647356d231a3dcab8a74fbac/miner/worker.go#L1881-L1906

**Comment by krasi-georgiev** [comment]
@avalonche ?

**Comment by cliff0412** [comment]
> When the TX is in the mempool the coinbase transfer should also be ignored.
> 
> It this code
> 
> https://github.com/flashbots/builder/blob/8caba1f96ff5adf5647356d231a3dcab8a74fbac/miner/worker.go#L1881-L1906

wondering why line 1889 is 
```go
coinbaseDelta.Sub(coinbaseDelta, gasFeesTx)
```
does coinbaseDelta already includes gasFeesTx so has to deduct here
