### ISSUE TITLE
Why is my builder creating blocks of zero values?

### ISSUE THREAD

**Issue by h4ck3rk3y** [flashbots/builder#89]
I am a maintainer at Kurtosis(a dev tool) and I am adding support for MEV to our Ethereum packages. The intent is to give people a private testnet of arbitrary size and clients where they can have MEV components. For the sake of this discussion I will be focussed on this package -

https://github.com/kurtosis-tech/geth-lighthouse-mev-package and specifically the `demo` tag.

Running `kurtosis run github.com/kurtosis-tech/geth-lighthouse-mev-package@demo` spins up an Ethereum network with a lighthouse validator/beacon client, a builder execution node (I am using my own image at h4ck3rk3y/builder as the project isn't publishing images yet), mev-boost, mev-relay-api, mev-relay-website, mev-relay-housekeeper nodes and mev-flood.

For some reason the Relay API is constantly complaining about blocks being 0 value. Looking at the builder logs and running `get_enginePayloadV2` on them I can see that the blocks indeed have value 0 in the JSON output.

The network is configured in a way where the suggested fee recipient & the eth.accounts[0] address is the address mentioned here https://github.com/kurtosis-tech/eth-network-package/blob/main/src/prelaunch_data_generator/genesis_constants/genesis_constants.star#L11-L15. The transactions I am running are increasing the balance of this address. Based on my understanding with `block level scoring` the block value should be greater than 0 but its stuck at 0 and the mev relay tool discards such blocks.

I have recorded some videos on loom that illustrate this further - 

https://www.loom.com/share/c1160e069fef49e0bbc38a39a686a150?sid=2b86a1d8-6585-4a3b-b78c-c7a0c3202dfd
https://www.loom.com/share/8bc3ba0c81b34851abb9d7c2cbf1b9d2?sid=be396f6d-2a38-4e9e-8b24-a421c48d25a3

Does anyone know whats going on? Some help would be appreciated.

I am not sure what the right avenue for this question is. If it isn't this Repo let me know where I should ask. Thank you!

**Comment by avalonche** [comment]
Seems like the issue stemming from `BUILDER_TX_SIGNING_KEY` not being set

**Comment by h4ck3rk3y** [comment]
This was indeed due to `BUILDER_TX_SIGNING_KEY` not being set!
